### ISSUE TITLE
Pridávanie dodávateľov a kategórií

### ISSUE THREAD

**Issue by jgavura** [TIS2023-FMFI/dodavanie-komponentov#22]

**Comment by jgavura** [comment]
https://learn.microsoft.com/en-us/power-pages/getting-started/tutorial-dataverse-website

**Comment by Raamxie** [comment]
> https://learn.microsoft.com/en-us/power-pages/getting-started/tutorial-dataverse-website

Nie je treba, v nastaveniach listu sa dajú nastaviť akcie ako pridať, zobraziť, upraviť a vymazať.
