### ISSUE TITLE
Filtrovanie

### ISSUE THREAD

**Issue by jgavura** [TIS2023-FMFI/dodavanie-komponentov#43]

**Comment by Raamxie** [comment]
https://ulrikke.akerbak.com/2022/01/29/date-range-filer-for-lists-on-power-apps-portals/
https://netwoven.com/dynamics-365/how-to-add-date-range-filter-controls-in-entity-list-in-dynamics-365-portal/

**Comment by Raamxie** [comment]
https://www.c-sharpcorner.com/article/power-pages-dynamic-execution-of-long-fetchxml-without-batch2/
https://stackoverflow.com/questions/62880091/how-to-dynamically-change-fetchxml-filters-in-dynamics-portal-using-liquid-templ

**Comment by p-jancarova** [comment]
Filtrovanie váhy môže byť pomocou checkboxov - možnosti 1g - 100g, 100g - 200g,... až po 1000g+

Váha je na 1 kus!!
