### ISSUE TITLE
Napísať katalóg požiadaviek

### ISSUE THREAD

**Issue by Raamxie** [TIS2023-FMFI/dodavanie-komponentov#5]

**Comment by Raamxie** [comment]
Link na KP:
https://drive.google.com/drive/u/0/folders/1ZaBrjrRelgte--FIDH2Wsh7nww76ezue

**Comment by Raamxie** [comment]
Rozdelenie kapitol:
1. Vladislav
2. Paulína
3. Michal, Juraj

**Comment by p-jancarova** [comment]
Katalóg požiadaviek bol skontrolovaný a schválený zadávateľom.
