### ISSUE TITLE
Tvorba návrhu

### ISSUE THREAD

**Issue by jgavura** [TIS2023-FMFI/dodavanie-komponentov#7]
- [x] Podrobná špecifikácia vonkajších interfejsov
- [x] Podrobný dátový model perzistentných údajov
- [x] Návrh používateľského rozhrania
- [x] Zrozumiteľný a jednoznačný návrh implementácie
- [x] Plán implementácie

**Comment by p-jancarova** [comment]
Odkaz na Návrh používateľského rozhrania:
https://app.moqups.com/Btfc88FFW3F0gB8LWsJ0bUglBCNyvvHH/view/page/ad64222d5

**Comment by p-jancarova** [comment]
Odkaz na Návrh systému (Google drive):
https://drive.google.com/drive/u/1/folders/1ZaBrjrRelgte--FIDH2Wsh7nww76ezue

**Comment by p-jancarova** [comment]
Odkaz na UML diagramy:
https://app.moqups.com/vn3A82ARl8pK8htBBbJoIQt6jNZMgE6a/edit/page/a83aeb934

**Comment by jgavura** [comment]
Odkazy na Power prostredie (1. verzia):
https://make.powerpages.microsoft.com/e/a7128d7b-80ab-ea9d-8e68-902c924cd047/sites/82fd24f4-9a0d-43f9-8cc2-f94a0322347a/pages#webpages/e6fbdbc2-d477-4a53-81dc-a983b3a16da2
https://make.powerapps.com/environments/a7128d7b-80ab-ea9d-8e68-902c924cd047/home

**Comment by jgavura** [comment]
Odkaz na Power prostredie (2. verzia):
https://make.powerpages.microsoft.com/e/a7128d7b-80ab-ea9d-8e68-902c924cd047/sites/3057a996-5180-46be-9c7d-619a213bf164#webpages/0be04d03-bdbf-4d23-9360-eb5f7d2dd2ea
